# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#using-role-dependencies
---
dependencies:
  - role: mirror_images
  - role: fbc-catalog
  - role: check-resource
...
