---

# pyxis_identifier field will be set to the general pyxis_identifier
# variable that is described in the pyxis role, or to '' if not
# providing that variable, but note that, if you do not define
# pyxis_identifier, preflight may fail in future releases where the
# field is mandatory.
- name: Include new operators in operator_data
  set_fact:
    operator_data: "{{ operator_data +
      [ { 'bundle_image'    : item.installPlans[0].bundleImage,
          'index_image'     : item.installPlans[0].indexImage|default(''),
          'pyxis_identifier': pyxis_identifier|default('') } ]
    }}"
  when:
    - item.installPlans[0].bundleImage is defined
    - item.installPlans[0].bundleImage | length
    - not item.installPlans[0].bundleImage in operator_bundles

- name: Print operator_data variable
  debug:
    msg: "{{ operator_data }}"

...
