---

# Namespace not deleted here, even if being the same used for cnf-cert. To be deleted in partner hooks
- name: Delete the partner deployment
  shell: |
    set -ex
    oc delete deployment partner -n {{ dci_openshift_app_ns }}

...
