---
# Deleting resources created by the CNF Cert Suite to support the execution
- name: Clean CNF Cert Suite resources
  block:
  - name: Check if debug daemonset exists
    community.kubernetes.k8s_info:
      api_version: v1
      kind: DaemonSet
      name: debug
      namespace: cnf-suite
    register: debug_daemonset

  - name: Delete the debug daemonSet
    community.kubernetes.k8s:
      api_version: v1
      kind: DaemonSet
      name: debug
      state: cnf-suite
    when: debug_daemonset.resources|length > 0
  when:
   - tnf_postrun_delete_resources|bool
   - test_network_function_version is version("v4.1.7", ">=") or test_network_function_version == "HEAD"

# When tnf_git_dir contains a folder from the PR, it is not a problem to
# remove the content from there because it is also present under the PR
# directory, which is removed after finishing the job thanks to test-runner
- name: Delete temporary directory for git repos
  file:
    path: "{{ tnf_git_dir.path }}"
    state: absent
  when:
    - tnf_git_dir is defined
    - tnf_git_dir.path is defined

...
