---
- name: Handle the situation when cert project already exists
  include_role:
    name: create-certification-project
    tasks_from: check_if_container_project_exists
  when: check_for_existing_projects | bool

- name: Create openshift-cnf project
  include_role:
    name: create-certification-project
    tasks_from: create_project

#Update mandatory params are not needed for now

- name: Attach Product List ID to openshift-cnf project when cert_listings is defined
  include_role:
    name: create-certification-project
    tasks_from: attach_product_listing
  when: cert_listings is defined
...
