---
- name: Openshift-cnf Project Creation Test Vendor Validation
  block:
    - name: "Create Openshift-cnf Certifcation Project"
      vars:
        current_cnf_name: "{{ cnf.cnf_name }}"
      include_tasks: create_openshift_cnf_project.yml
      loop: "{{ cnf_to_certify }}"
      loop_control:
        loop_var: cnf
  when: project_type == 'openshift_cnf'
...
