---
# These variables have the lowest priority of any variables available, and can be easily overridden by any other variable, including inventory variables.
ocp_version_full: 4.7
kubeconfig_path: /home/{{ user }}/.kube/config
do_chart_verifier: false
chart_verifier_image: quay.io/redhat-certification/chart-verifier:1.3.0
logs_dir: /tmp
dci_charts:
  -
    name: valid_chart
    chart_file: "https://github.com/redhat-certification/chart-verifier/raw/main/pkg/chartverifier/checks/chart-0.1.0-v3.valid.tgz"
    install: false
...
