---
chart_verifier_function_repo: https://github.com/redhat-certification/chart-verifier
chart_verifier_function_version: "HEAD"
dci_openshift_app_image: "quay.io/chart-verifier/chart-verifier:latest"
cv_if: eth0
cv_operators_regexp: ""
cv_cnfs_regexp: ""
cv_exclude_connectivity_regexp: ""
cv_suites: "is-helm-v3 has-readme contains-test has-kubeversion contains-values-schema not-contains-crds not-contain-csi-objects images-are-certified helm-lint contains-values"
cv_targetpodlabels_name: ""
cv_targetpodlabels_value: ""
cv_run_chart_verifier_test: false
# OC Debug image
# This is the tools image from the 4.7.20 release
# https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.7.20/release.txt
# Not sure what this is.
tnf_debug_image: "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0f5ce898fbad3671fecd6f797130f950fb1abdbaf0d8154c22e2b59c74e3a918" # v4.7.20
