---
# These variables have the lowest priority of any variables available, and can be easily overridden by any other variable, including inventory variables.
cv_image: quay.io/redhat-certification/chart-verifier:1.3.0
cv_job_logs: /tmp/
cv_dci_charts: 
  -
    name: valid_chart
    chart: "https://github.com/redhat-certification/chart-verifier/raw/main/pkg/chartverifier/checks/chart-0.1.0-v3.valid.tgz"
...
