---
do_preflight_tests: true
preflight_artifacts: /var/tmp/preflight_artifacts
preflight_containers_to_check:
  - quay.io/opdev/preflight:stable
  - quay.io/testnetworkfunction/cnf-test-partner:latest
