---
# scorecard vars
operator_sdk_tool_path: "/usr/local/bin/operator-sdk-flag"

# preflight vars
# tmp preflight version until we'll have a new preflight release
# with that fix: https://github.com/redhat-openshift-ecosystem/openshift-preflight/pull/332
preflight_version: quay.io/opdev/preflight:d264b0a7a103f4aaee763a704f449409ad6b76a5

preflight_operators_to_check:
  - {
    image: 'quay.io/rh-nfv-int/testpmd-operator-bundle@sha256:5e28f883faacefa847104ebba1a1a22ee897b7576f0af6b8253c68b5c8f42815',
    index_image: 'quay.io/tkrishtop/index-testpmd-operator-bundle:v0.2.9',
    }
  - {
    image: 'quay.io/opdev/simple-demo-operator-bundle@sha256:eff7f86a54ef2a340dbf739ef955ab50397bef70f26147ed999e989cfc116b79',
    index_image: 'quay.io/opdev/simple-demo-operator-catalog:v0.0.3',
    }

...
