---
# Define preflight_binary if you intend to use it for check container tests.
# preflight_binary: https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.0.8/preflight-linux-amd64
# If empty, podman image preflight_image would be used for both
# check container and check operator.
# Preflight 1.0.8 requires to use podman image everywhere.
# Preflight 1.1.0-* pre-releases require to use binary for check container
# because some container tests fail.
# The next Preflight release will require to use podman run again.
preflight_binary: ""
preflight_image: quay.io/opdev/preflight:1.0.8
# Use the next two variables if instead of using ready image and binary
# you would prefer to take a defined Preflight branch and build image and
# binary out of this branch.
preflight_repo: "https://github.com/redhat-openshift-ecosystem/openshift-preflight.git"
preflight_branch: "main"
# This namespace will be used by Preflight tool
# during check operator tests
preflight_namespace: preflight-testing
preflight_custom_ca: ""
preflight_podman_ca: ""
...
