---
preflight_version: 0.0.0
preflight_artifacts: /var/tmp/preflight_artifacts
preflight_containers_to_check:
  - quay.io/opdev/preflight:stable
  - quay.io/testnetworkfunction/cnf-test-partner:latest
preflight_operators_to_check:
  - quay.io/rh-nfv-int/testpmd-operator-bundle:v0.2.9
preflight_container_output:
  - "results.json"
  - "preflight.log"
preflight_operator_output:
  - "results.json"
  - "preflight.log"
  - "hashes.txt"

...
