---
# this version contains scorecard busybox fix and runtime-assets
preflight_version: quay.io/opdev/preflight:1.0.2

# preflight check operator vars
preflight_operators_to_check:
  - { image: 'quay.io/rh-nfv-int/testpmd-operator-bundle:v0.2.9', index_image: 'quay.io/tkrishtop/index-testpmd-operator-bundle:v0.2.9' }

preflight_operator_output:
  - results.json
  - results-junit.xml
  - preflight.log
  - hashes.txt
  - operator_bundle_scorecard_BasicSpecCheck.json
  - operator_bundle_scorecard_OlmSuiteCheck.json

...
