---

- name: "Copy chart-verifier-partner image."
  shell: |
    set -ex
    skopeo copy --authfile {{ provisionhost_registry_creds }} \
    docker://quay.io/redhat-certification/chart-verifier:latest \
    docker://{{ provisionhost_registry }}/chart-verifier/chart-verifier-partner:latest

# tnf_debug_image_name starts with '/'
- name: "Copy image to be used with oc debug."
  shell: |
    set -ex
    skopeo copy --authfile {{ provisionhost_registry_creds }} \
    docker://quay.io{{ tnf_debug_image | regex_search('/.*') }} \
    docker://{{ provisionhost_registry }}{{ cv_debug_image | regex_search('/.*') }}

...
