---
# 1/ required by preflight dependencies https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.7.20/release.txt
# TODO: failing then mirroring the image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bf657092557cf90be41f7d5a382c9734759afe0feab480732d70ad960b2a407d
# 2/ scorecard-storage: https://github.com/operator-framework/operator-sdk/pull/6425/files
# 3/ scorecard-untar: https://github.com/operator-framework/operator-sdk/pull/6425/files 
images:
  - quay.io/operator-framework/scorecard-storage@sha256:a3bfda71281393c7794cabdd39c563fb050d3020fd0b642ea164646bdd39a0e2
  - quay.io/operator-framework/scorecard-untar@sha256:2e728c5e67a7f4dec0df157a322dd5671212e8ae60f69137463bd4fdfbff8747
...
