---
- name: Delete preflight container
  shell: |
    podman rm preflight
  ignore_errors: true

- name: Delete directory with preflight output
  file:
    path: "{{ preflight_artifacts }}"
    state: absent
...
