- name: Check if commands were extracted
  stat:
    path: "{{ preflight_binary_dir }}"
    get_checksum: no
  register: preflight_dir

- name: Create preflight directory if not exists
  file:
    path: "{{ preflight_binary_dir }}"
    state: directory
    recurse: yes
    # ansible_user is not defined if d-o-a-a runs in the isolated mode
    # check <change_id> $HOME/<cluster_path>/kubeconfig example-cnf
    # owner: "{{ ansible_user }}"
  become: true

- name: Download preflight if not exists
  get_url:
    url: "https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/{{ preflight_binary_version}}/preflight-linux-amd64"
    dest: "{{ preflight_binary_dir }}/preflight"
    mode: "0755"
  when: not preflight_dir.stat.exists
