---
- name: Copy authentication config
  copy:
    src: "{{ pullsecret_tmp_file.path }}"
    dest: "{{ preflight_tmp_dir.path }}/config.json"

- name: Update preflight_podman_auth variable for preflight command
  set_fact:
    preflight_podman_auth:
      "-v {{ preflight_tmp_dir.path }}/config.json:/opt/config.json"
...
