---
- name: Set location of preflight binary preflight_binary_dir
  set_fact:
    preflight_binary_dir: "{{ preflight_tmp_dir.path }}/preflight/{{ preflight_binary.split('/')[-2] }}"

- name: Create preflight directory
  file:
    path: "{{ preflight_binary_dir }}"
    state: directory
    recurse: yes

# Using uri instead of get_url due to this bug:
# https://github.com/ansible/ansible/issues/68843
- name: Download preflight
  uri:
    url: {{ preflight_binary }}
    dest: {{ preflight_binary_dir }}/preflight
    mode: "0755"
    return_content: true
    follow_redirects: true
  register: preflight_file
  retries: 3
  delay: 10
  until: preflight_file is not failed

...
