---
- name: Verify that preflight tests were run
  fail:
    msg: Impossible to submit preflight results to pyxis. Please ensure that preflight tests were run.
  when:
    - preflight_operators_to_check is undefined
    - preflight_operators_to_check | type_debug != "list"
  ignore_errors: true

- name: Verify that pyxis credentials are provided
  fail:
    msg: Impossible to submit preflight results to pyxis. Please provide pyxis_identifier and pyxis_apikey.
  when:
    - pyxis_identifier is undefined
    - pyxis_apikey is undefined
  ignore_errors: true

- name: Submit preflight cert results for each operator
  include_tasks: submit_test_results.yml
  loop: "{{ preflight_operators_to_check }}"
  loop_control:
    loop_var: operator
  when:
    - preflight_operators_to_check is defined
    - pyxis_identifier is defined
    - pyxis_apikey is defined
  ignore_errors: true
...